# Archivo netlify.toml simplificado para un proyecto sin framework

[build]
  # El directorio a publicar (donde está tu index.html)
  publish = "frontend/"
  
  # El directorio donde están tus funciones de backend
  functions = "netlify/functions/"

# Redirección para que tu frontend pueda llamar al backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
